[E] 개인 설정 화면 버그 픽스
boostcampwm-2021/iOS01-Booster pull request #132
Opened 2021-11-20 11:07 UTC by s1gnature

### 작업 내용
[E-89] 목표바꾸기 페이지 내 기존 목표 값 표기
[E-80] 마이페이지 내 기존 값 표기
UIAlertController+Extenstion 내부에 simpleAlert에 새로운 파라미터 추가
### 체크리스트
- [x] #128 버그 픽스
- [x] #129 버그 픽스
- [x] NavigationBar Title 제대로 표시 되지 않는 현상 수정
- [x] UIAlertController 이후 VC가 Pop 되지 않는 현상 수정

### 구현 설명
- UIAlertController+Extenstion 내부에 simpleAlert에 새로운 파라미터 추가
확인 버튼에 대한 action Closure를 받을 수 있도록 추가. default 값 nil을 통하여 기존 코드에 지장 없도록 구현
사용법
~~~swift
alert = UIAlertController.simpleAlert(title: title,
                                                              message: message,
                                                              action: { (_) -> Void in
                            self?.navigationController?.popViewController(animated: true)
                            return
})
~~~
### 하고싶은 말
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-20 at 19 59 39](https://user-images.githubusercontent.com/48645631/142724012-1e9f8d5a-fa0a-4627-ab68-07531ca99050.png)
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-20 at 19 59 41](https://user-images.githubusercontent.com/48645631/142724020-dbdcdeae-43ea-4457-a15e-dcb174e4bdd8.png)

2021-11-20 11:17 UTC, KTH-INHA-16 requested changes
고생하셨스무니다~~~~~

2021-11-20 11:17 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +        } else {
나중에 동작 추가해 주실꺼죠?? ㅜㅜ

2021-11-20 11:17 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +            present(alert, animated: true, completion: nil)
let title
let message
호~~~우~~~

2021-11-20 11:17 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
>      }
여기서 바로 `navigationItem.title = title` 로 가도 될것 같다는 생각이 들어용 ㅎㅎ

2021-11-20 11:21 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +        } else {
ㅋㅋㅋㅋ네네 이부분은 저희 목표 걸음수 CoreData에 업데이트 되는대로 바로 추가하려구요!

2021-11-20 11:21 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +            present(alert, animated: true, completion: nil)
앗 요거 지금 바로 수정해서 올려드릴게요~

2021-11-20 11:23 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
>      }
그게 더 가독성이 좋겠네요!! 저렇게 하면 탭바가 보였을 때 탭바 타이틀이 바뀌더라구요! 저걸로 바꿔둘게요~~

2021-11-20 11:36 UTC, rose6649 commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +
아래는 configureUI고,
위는 navigationBarTitleConfigure인데,
위도 configureNavigationBarTitle하면 좀더 맞춘 느낌이 나지 않을까용 ?! 🥺

2021-11-20 11:37 UTC, rose6649 commented on Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
>          configureUITextField()
🥺🥺🥺

2021-11-20 11:41 UTC, rose6649 commented on Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
> +                        return
여기 return 이 꼭 필요한가용? 🥺

2021-11-20 11:42 UTC, rose6649 commented on Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
>                      dump(error)
dump는 ! ! !

2021-11-20 11:44 UTC, rose6649 approved these changes
주말작업 수고하셨어용 ㅠㅠㅠ 👍 마이페이지는 명섭님덕분에 완성도가 올라가네요!

2021-11-20 12:02 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
> +
앗.. 그러게요 이부분은 맞춰야 할 필요가 있겠네요 ㅠㅠㅠ 반영할게요!!

2021-11-20 12:02 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
>          configureUITextField()
😢😢😢

2021-11-20 12:02 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
> +                        return
popViewController의 반환 값이 UIViewController라 리턴타입이 Void여야만 해서 return을 작성하지 않으면 에러가 나더라구요...! 이거 마음에 안들긴 하는데 더 좋은 방법이 있다면 수정해볼게요!

2021-11-20 12:02 UTC, s1gnature commented on Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
>                      dump(error)
요기는 제거하도록 하겠습니다~~

2021-11-22 02:03 UTC, KTH-INHA-16 approved these changes

2021-11-22 02:16 UTC, Hani-Levenshtein approved these changes

2021-11-22 02:31 UTC, merged