[A, D] DetailFeed 리팩토링 및 뷰 재사용 추가
boostcampwm-2021/iOS01-Booster pull request #186
Opened 2021-11-27 17:27 UTC by rose6649

### 작업 내용
- DetailFeedVC, VM, model 작업
- milestone, coordinate 배열 구조체 타입 변경되면서 메소드 로직 분리
- 세개 3열 record ( kcal, time, km 커스텀 뷰) 생성 -> 재사용성 높임. 홈/피드 모두 사용 가능. (트래킹도 사용할수있을듯합니다)

### 체크리스트
- [x] #104 

### 구현 설명
- VC에 있는 뷰작업들을 다 뷰로 옮겨서 VC의 역할을 좀 줄였습니다.
-  km, kcal, time의 기록을 담고 있는 UI뷰를 커스텀뷰를 만들어 , 다른 화면에서도 재사용성을 높였습니다.
- 기존 VC에서 가지고 있던 colors UIcolor 배열을 없앴습니다. 따로, milestone과 coordinate구조체에 연결시켰습니다.

### 하고싶은 말

2021-11-28 07:21 UTC, KTH-INHA-16 requested changes
이젠 코드로도 UI를 아릅답고 완벽하게 하시는거 보니까. 다들 역시 iOS 마스터들이군여 ㅎㅎ 주말에도 고생했어여~

2021-11-28 07:21 UTC, KTH-INHA-16 commented on Booster/Booster/Extensions/UIView+Extension.swift
> +                                           height: self.frame.size.height)
띄워 쓰기가 수상하네요? ㅎㅎ

2021-11-28 07:21 UTC, KTH-INHA-16 commented on Booster/Booster/Models/Coordinate.swift
> +        return Double(index) / Double(coordinates.count)
나눌 때 혹시 0으로 나누는 경우 없을까요?

2021-11-28 07:21 UTC, KTH-INHA-16 commented on Booster/Booster/Usecases/DetailFeedUsecase.swift
> +                observer.on(.error(TrackingError.modelError))
onError도 괜찮을 것 같아요!

2021-11-28 07:21 UTC, KTH-INHA-16 commented on Booster/Booster/Usecases/DetailFeedUsecase.swift
>                  return Disposables.create()
이 부분에서 혹시 종료가 되는 부분이면 
``` swift
Disposables.create {
    observer.onCompeleted()
}
```
이렇게도 하더라고요? 어떻게 생각하시나요?

2021-11-28 07:50 UTC, s1gnature approved these changes
주말에도 고생하셨습니다ㅠㅠㅠㅠㅠ 남은 기간 화이팅!!

2021-11-28 07:50 UTC, s1gnature commented on Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
> +        return trackingModel.value.milestones.milestone(at: coordinate)
이부분은 빠르게 고쳐보겠습니다ㅠㅠㅠ

2021-11-28 07:50 UTC, s1gnature commented on Booster/Booster/Views/Feed/DetailFeedMapView.swift
> +        layer.cornerRadius = frame.height / 17
17을 변수로 빼는것도 좋아보여요!!!

2021-11-28 11:54 UTC, Hani-Levenshtein approved these changes

2021-11-28 11:54 UTC, Hani-Levenshtein commented on Booster/Booster/Extensions/UIView+Extension.swift
> +    func snapshot() -> UIImage? {
뷰의 어떤 상태에 대한 스냅샷인지 메서드에 명시되면 좋을 것 같아용

2021-11-28 11:54 UTC, Hani-Levenshtein commented on Booster/Booster/Models/Coordinate.swift
> +        return Double(index) / Double(coordinates.count)
이번 프로젝트에서 0으로 나누는거에 많이 고통을 겪었는데
태훈님 리뷰덕에 많은 도움이 됐어용

2021-11-28 11:54 UTC, Hani-Levenshtein commented on Booster/Booster/Views/Utils/ThreeColumnRecordView.swift
> +    private func configure() {
아래 메서드도 뭘 configure하는지 메서드에 명시되면 좋을 것 같아용

2021-11-28 11:54 UTC, Hani-Levenshtein commented on Booster/Booster/Views/Utils/ThreeColumnRecordView.swift
> +        kmLabel.centerYAnchor.constraint(equalTo: kcalLabel.centerYAnchor).isActive = true
multiplier의 값을 예쁘게 표현하면 좋을거같아용

2021-11-28 13:10 UTC, rose6649 commented on Booster/Booster/Extensions/UIView+Extension.swift
> +                                           height: self.frame.size.height)
꺄악 수정할게요! ! !!!

2021-11-28 13:11 UTC, rose6649 commented on Booster/Booster/Models/Coordinate.swift
> +        return Double(index) / Double(coordinates.count)
0 ..! 0...! 나누는 경우를 생각해보고 다시 수정해볼게요!

2021-11-28 13:12 UTC, rose6649 commented on Booster/Booster/Usecases/DetailFeedUsecase.swift
> +                observer.on(.error(TrackingError.modelError))
아! 넹 ㅎㅎㅎㅎ

2021-11-28 13:13 UTC, rose6649 commented on Booster/Booster/Usecases/DetailFeedUsecase.swift
>                  return Disposables.create()
onCompleted로 불려야하는지 고민해보고 결정해보겠습니당!! 🥺👍

2021-11-28 13:14 UTC, rose6649 commented on Booster/Booster/Views/Feed/DetailFeedMapView.swift
> +        layer.cornerRadius = frame.height / 17
고려해보겠습니다 :D 👯

2021-11-28 13:15 UTC, rose6649 commented on Booster/Booster/Extensions/UIView+Extension.swift
> +    func snapshot() -> UIImage? {
흠.! 이게그냥 뷰 하나 통 전체를 고대로 캡쳐하는 부분인데..! 
더 좋은 네이밍이 생각나면 바꿔보도록 하겠습니다 :)

2021-11-28 13:16 UTC, rose6649 commented on Booster/Booster/Views/Utils/ThreeColumnRecordView.swift
> +    private func configure() {
감사합니다~~ ㅎㅎㅎㅎ

2021-11-28 13:17 UTC, rose6649 commented on Booster/Booster/Views/Utils/ThreeColumnRecordView.swift
> +        kmLabel.centerYAnchor.constraint(equalTo: kcalLabel.centerYAnchor).isActive = true
값에 대해 네이밍을 붙이라는 의미일까요, 아니면 값이 딱 떨어지는 값이면 좋겠다는 말씀일까요 ?!
후자라면, 이게 UI 상에서 딱 들어맞게 간격이 예쁘게 보이는 값이 저 값이어서 해놨습니당! ㅜㅜ

2021-11-28 13:52 UTC, rose6649 commented on Booster/Booster/Models/Coordinate.swift
> +        return Double(index) / Double(coordinates.count)
여기서 0이 나누어져도 앱 크래쉬는 없습니다! 비율로 나오게 하는거라, 만약 0이면 검은색 path가 그려집니다 ㅎㅎ :)

2021-11-28 13:55 UTC, rose6649 commented on Booster/Booster/Usecases/DetailFeedUsecase.swift
>                  return Disposables.create()
저기 위에서 onError로 보내고 있는데, onCompleted로 보낼 이유가 충분하지 않아서 일단 둬야할것같네용 😢 에러가나면 컴플릿 메소드는 불리지 않기때문에...

2021-11-29 01:20 UTC, KTH-INHA-16 approved these changes

2021-11-29 01:20 UTC, merged