[#74] 홈페이지 시간별 걸음수 그래프 & usecase 추가
boostcampwm-2021/iOS01-Booster pull request #82
Opened 2021-11-14 08:34 UTC by rose6649

### 작업 내용
- 홈페이지 시간별 걸음수 그래프 및 usecase로 viewModel에서 분리

### 체크리스트
- [x] viewModel과 usecase 분리
- [x] 홈페이지 chartView 그래프 설정 

### 구현 설명
- healthKitManager 싱글톤에서 오늘의 데이터만 총합으로 가져오는 방식으로 구현했습니다.
- 중복되는 코드를 줄이고자 today distance, stepcount..등을 fetchTodayData 메소드 하나로 합쳤고, 옵션을 두어 설정가능하도록 변경했습니다.

### 하고싶은 말
- 그래프를 그릴 때, 빈 곳은 따로 비어졌다는 표시를 해줘야하는데, 혹시 그래프 코드에 따로 있을까요? 지금은 따로 뷰모델에서 빈 값은 넣어주도록 하고 있습니다.

2021-11-14 08:42 UTC, KTH-INHA-16 requested changes
주말동안 고생하셨습니다~

2021-11-14 08:42 UTC, KTH-INHA-16 commented on Booster/Booster/Usecases/HomeUsecase.swift
> +                                                    options: .strictStartDate)
retrieveTodayStartDate로 현재 Date를 넣어 다시 현재 Date를 반환하던데 여기서
`retrieveTodayStartDate(from:_)` 매서드를 만든 이유가 있을까요?

2021-11-14 08:42 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +                self?.configureHourlyChartView()
이 부분은 매서드로 분리하는 것도 좋아보이네요

2021-11-14 08:42 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            let stepRatio = CGFloat(step) / CGFloat(maxStep)
혹시 maxStep이 0이 되는 경우는 없을까요?

2021-11-14 08:42 UTC, KTH-INHA-16 commented on Booster/Booster/ViewModels/Home/HomeViewModel.swift
> +            }
use case로 분리가 아주 탁월하네요

2021-11-14 08:42 UTC, KTH-INHA-16 commented on Booster/Booster/ViewModels/Home/HomeViewModel.swift
> +            let km = distance / 1000
여기서 차라리 meter가 아니라 kilo도 있는데 kilo를 사용하는 건 별로인가요?

2021-11-14 09:04 UTC, rose6649 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +                self?.configureHourlyChartView()
앗.. 분리해보도록 할게요! :)!

2021-11-14 09:07 UTC, rose6649 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            let stepRatio = CGFloat(step) / CGFloat(maxStep)
아마 모든 데이터가 없으면 0으로 될 텐데 stepRatio도 0으로 가져가면 되는 부분이라
로직 상 문제는 없습니다 ㅎㅎ!

2021-11-14 09:13 UTC, rose6649 commented on Booster/Booster/ViewModels/Home/HomeViewModel.swift
> +            let km = distance / 1000
kilo 가 킬로미터인줄 몰랐네요.. ㅎㅎ 감사합니다! 수정하겠습니다 ㅎㅎ

2021-11-14 09:19 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            let stepRatio = CGFloat(step) / CGFloat(maxStep)
여기서 나눌 때 maxStep이 0이되서 에러가 발생할 것 같긴한데, 0 인경우는 없나요?

2021-11-14 09:24 UTC, rose6649 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            let stepRatio = CGFloat(step) / CGFloat(maxStep)
아하-! 넵 이 부분 조건달아서 리턴처리 하겠습니당 감사해요 !!

2021-11-14 09:27 UTC, rose6649 commented on Booster/Booster/ViewModels/Home/HomeViewModel.swift
> +            let km = distance / 1000
kilo가 HKUnit에 있나요 혹시?? .>! (수정하려보니 없어가지구요)

2021-11-15 02:02 UTC, KTH-INHA-16 approved these changes

2021-11-15 02:19 UTC, s1gnature approved these changes
코드가 재사용이 유용하도록 분리도 되어있고 깔끔하네요! 고생하셨습니다!

2021-11-15 02:19 UTC, s1gnature commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +        var strings = [String](repeating: "", count: 25)
숫자 25가 무엇을 의미하는 건가요?! 의미가 있거나 크다면 따로 변수로 빼서 관리하는것은 어떨까요!!

2021-11-15 02:25 UTC, Hani-Levenshtein approved these changes

2021-11-15 02:25 UTC, Hani-Levenshtein commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            self.todayTotalStepCountLabel.layer.opacity = 1
opacity에 대한 enum: Int 를 만들면 어떨까욥

2021-11-15 02:27 UTC, merged