[refactor] 뷰 레이아웃 & 컬러 수정
boostcampwm-2021/iOS01-Booster pull request #86
Opened 2021-11-14 11:43 UTC by rose6649

### 작업 내용
- 전체적인 레이아웃 및 컬러 수정을 했습니다.
- 기존 제 역할이 아닌 세밀한 부분들은 회의를 먼저 하고 수정해야할 것 같아 수정하지 않았습니다.

### 체크리스트
- [x] 기록 저장 화면에서 제목이랑 content랑 앞단이 살짝 안맞는 현상
- [x] 통계 그래프에서 폰트 사이즈 수정 및 컬러 수정
- [x] 다크모드에서는 tracking에서 총걸음수와 뒤로가기 틴트 컬러가 EDEDED(boosterLabel)색상으로 수정되어야함
- [x] 컬러모드에서의 컬러 수정이 필요 -> 통계 백그라운드 색상 컬러 수정

### 구현 설명

### 하고싶은 말

2021-11-14 14:02 UTC, KTH-INHA-16 requested changes

2021-11-14 14:02 UTC, KTH-INHA-16 commented on Booster/Booster/ViewControllers/Home/HomeViewController.swift
> +            stepRatios.append(stepRatio)
이부분은 합칠 때 조심해야할 것 같네요

2021-11-14 14:02 UTC, KTH-INHA-16 commented on Booster/Booster/ViewModels/Home/HomeViewModel.swift
> +            self?.homeModel.value.km = km
이 부분도 합칠 때 조심해야할 것 같습니다

2021-11-15 02:04 UTC, KTH-INHA-16 approved these changes

2021-11-15 02:14 UTC, s1gnature approved these changes
주말동안 고생하셨어요!!

2021-11-15 02:27 UTC, Hani-Levenshtein approved these changes

2021-11-15 02:27 UTC, merged